<?php
/**
 * author      : Yxhsea.
 * email       : Yxhsea@foxmail.com
 * createTime  : 2017/8/22 21:24
 * description :
 */
namespace app\admin\controller;
use think\Controller;

class Base extends Controller{

    //初始化
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $rootUrl = $this->request->root(true);
        $static = Config('TMPL_PARSE_STRING');//静态资源文件路径
        foreach ($static as $key => $value){
            $this->assign('_'.$key,$rootUrl.$value);
        }
    }

    public function common(){
        return $this->fetch();
    }
}